version: "3.8"
services:

  my_database:
    container_name: mysql-db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1122
      MYSQL_PASSWORD: 1234
      MYSQL_USER: ogleh
      MYSQL_DATABASE: country