spring:
  application:
    name: countries-app

  datasource:
    url: jdbc:mysql://localhost:3306/country
    password: 1234
    username: ogleh
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect